Create table role(
    role_id bigint generated by default as identity,
    name varchar(255) not null ,
    primary key (role_id)
);
Create table user_role(
    id bigint generated by default as identity,
    user_id bigint generated by default as identity,
    role_id bigint generated by default as identity,
    PRIMARY KEY (id),
    FOREIGN KEY (role_id)
        REFERENCES role (role_id),
    FOREIGN KEY (user_id)
        REFERENCES "user" (user_id)
);
